---
name: registripe_addons
---
RegistrableEvent:
  extensions:
    - RegistrableEventAddOnExtension
EventAttendee:
  extensions:
    - EventAttendeeAddOnExtension
EventAttendeeController:
  extensions:
    - EventAttendeeControllerAddOnExtension
TicketSelectionController:
  extensions:
    - EventAttendeeControllerAddOnExtension

AttendeeTicketSelection:
  calculators:
    - AddOns
